//DEFAULT
export const FETCHING_START = "FETCHING_START"
export const FETCHING_ERROR = "FETCHING_ERROR"
export const FETCHING_PROCESSED = "FETCHING_PROCESSED"

//ITEM & CATEGORY
export const CATEGORY_FETCHED = "CATEGORY_FETCHED" 
export const CATEGORY_DATA_FETCHED = "CATEGORY_DATA_FETCHED"
export const SPECIFIC_ITEM_FETCHED = "SPECIFIC_ITEM_FETCHED"
export const FEATURED_PRODUCT_FETCHED = "FEATURED_PRODUCT_FETCHED"

// CART CONSTANTS
export const CART_FETCHED = "CART_FETCHED"

// AUTHENTICATION
export const VERIFY_PHONE_NUMBER_PROCESSING = "VERIFY_PHONE_NUMBER_PROCESSING"
export const VERIFY_PHONE_NUMBER_PROCESSED = "VERIFY_PHONE_NUMBER_PROCESSED"
export const VERIFY_PHONE_CODE_PROCESSING = "VERIFY_PHONE_CODE_PROCESSING"
export const VERIFY_PHONE_CODE_PROCESSED = "VERIFY_PHONE_CODE_PROCESSED"
export const LOGOUT_PROCESSED = "LOGOUT_PROCESSED"
export const USER_DATA_FETCHED = "USER_DATA_FETCHED"

// SEARCHING
export const SEARCHING_START = "SEARCHING_START"
export const SEARCHING_FOUND = "SEARCHING_FOUND"
export const SEARCHING_ERROR = "SEARCHING_ERROR"

// ORDER CONSTANTS
export const ORDER_FETCHED = "ORDER_FETCHED"
// BANNER FETCHING
export const BANNER_FETCHED = "BANNER_FETCHED"
// TERM & CONDITION
export const TC_FETCHED = "TC_FETCHED"
// LOCATION
export const LOCATION_FETCHED = "LOCATION_FETCHED"

export const PRICE_CHECKER_UPDATE = "PRICE_CHECKER_UPDATE"

export const PROMO_APPLIED = "PROMO_APPLIED"
export const EMPTY_PROMO = "EMPTY_PROMO"
